#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PioneerET
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pioneeret")]
	public partial class PioneerETDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPioneerET_Assigned_Equipment(PioneerET_Assigned_Equipment instance);
    partial void UpdatePioneerET_Assigned_Equipment(PioneerET_Assigned_Equipment instance);
    partial void DeletePioneerET_Assigned_Equipment(PioneerET_Assigned_Equipment instance);
    partial void InsertPioneerET_Equipments_Inventory(PioneerET_Equipments_Inventory instance);
    partial void UpdatePioneerET_Equipments_Inventory(PioneerET_Equipments_Inventory instance);
    partial void DeletePioneerET_Equipments_Inventory(PioneerET_Equipments_Inventory instance);
    partial void InsertPioneerET_Fleets_Management(PioneerET_Fleets_Management instance);
    partial void UpdatePioneerET_Fleets_Management(PioneerET_Fleets_Management instance);
    partial void DeletePioneerET_Fleets_Management(PioneerET_Fleets_Management instance);
    partial void InsertPioneerET_Frac_Locations(PioneerET_Frac_Locations instance);
    partial void UpdatePioneerET_Frac_Locations(PioneerET_Frac_Locations instance);
    partial void DeletePioneerET_Frac_Locations(PioneerET_Frac_Locations instance);
    partial void InsertPioneerET_Frac_Locations_Headcount(PioneerET_Frac_Locations_Headcount instance);
    partial void UpdatePioneerET_Frac_Locations_Headcount(PioneerET_Frac_Locations_Headcount instance);
    partial void DeletePioneerET_Frac_Locations_Headcount(PioneerET_Frac_Locations_Headcount instance);
    partial void InsertPioneerET_Frac_Locations_Well(PioneerET_Frac_Locations_Well instance);
    partial void UpdatePioneerET_Frac_Locations_Well(PioneerET_Frac_Locations_Well instance);
    partial void DeletePioneerET_Frac_Locations_Well(PioneerET_Frac_Locations_Well instance);
    partial void InsertPioneerET_Locations_Fleets(PioneerET_Locations_Fleets instance);
    partial void UpdatePioneerET_Locations_Fleets(PioneerET_Locations_Fleets instance);
    partial void DeletePioneerET_Locations_Fleets(PioneerET_Locations_Fleets instance);
    partial void InsertPioneerET_Locations_Silos(PioneerET_Locations_Silos instance);
    partial void UpdatePioneerET_Locations_Silos(PioneerET_Locations_Silos instance);
    partial void DeletePioneerET_Locations_Silos(PioneerET_Locations_Silos instance);
    partial void InsertPioneerET_Notifications(PioneerET_Notifications instance);
    partial void UpdatePioneerET_Notifications(PioneerET_Notifications instance);
    partial void DeletePioneerET_Notifications(PioneerET_Notifications instance);
    partial void InsertPioneerET_Notifications_Recipients(PioneerET_Notifications_Recipients instance);
    partial void UpdatePioneerET_Notifications_Recipients(PioneerET_Notifications_Recipients instance);
    partial void DeletePioneerET_Notifications_Recipients(PioneerET_Notifications_Recipients instance);
    partial void InsertPioneerET_Options(PioneerET_Options instance);
    partial void UpdatePioneerET_Options(PioneerET_Options instance);
    partial void DeletePioneerET_Options(PioneerET_Options instance);
    partial void InsertPioneerET_Out_For_Repair(PioneerET_Out_For_Repair instance);
    partial void UpdatePioneerET_Out_For_Repair(PioneerET_Out_For_Repair instance);
    partial void DeletePioneerET_Out_For_Repair(PioneerET_Out_For_Repair instance);
    partial void InsertPioneerET_Repair_Locations(PioneerET_Repair_Locations instance);
    partial void UpdatePioneerET_Repair_Locations(PioneerET_Repair_Locations instance);
    partial void DeletePioneerET_Repair_Locations(PioneerET_Repair_Locations instance);
    partial void InsertPioneerET_SiloSets(PioneerET_SiloSets instance);
    partial void UpdatePioneerET_SiloSets(PioneerET_SiloSets instance);
    partial void DeletePioneerET_SiloSets(PioneerET_SiloSets instance);
    partial void InsertPioneerET_Standards(PioneerET_Standards instance);
    partial void UpdatePioneerET_Standards(PioneerET_Standards instance);
    partial void DeletePioneerET_Standards(PioneerET_Standards instance);
    partial void InsertPioneerET_Team_Management(PioneerET_Team_Management instance);
    partial void UpdatePioneerET_Team_Management(PioneerET_Team_Management instance);
    partial void DeletePioneerET_Team_Management(PioneerET_Team_Management instance);
    partial void InsertPioneerET_Users_from_LDAP(PioneerET_Users_from_LDAP instance);
    partial void UpdatePioneerET_Users_from_LDAP(PioneerET_Users_from_LDAP instance);
    partial void DeletePioneerET_Users_from_LDAP(PioneerET_Users_from_LDAP instance);
    partial void InsertPioneerET_Yard(PioneerET_Yard instance);
    partial void UpdatePioneerET_Yard(PioneerET_Yard instance);
    partial void DeletePioneerET_Yard(PioneerET_Yard instance);
    #endregion
		
		public PioneerETDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PioneerETDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PioneerETDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PioneerETDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PioneerET_Assigned_Equipment> PioneerET_Assigned_Equipment
		{
			get
			{
				return this.GetTable<PioneerET_Assigned_Equipment>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Equipments_Inventory> PioneerET_Equipments_Inventory
		{
			get
			{
				return this.GetTable<PioneerET_Equipments_Inventory>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Fleets_Management> PioneerET_Fleets_Management
		{
			get
			{
				return this.GetTable<PioneerET_Fleets_Management>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Frac_Locations> PioneerET_Frac_Locations
		{
			get
			{
				return this.GetTable<PioneerET_Frac_Locations>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Frac_Locations_Headcount> PioneerET_Frac_Locations_Headcount
		{
			get
			{
				return this.GetTable<PioneerET_Frac_Locations_Headcount>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Frac_Locations_Well> PioneerET_Frac_Locations_Well
		{
			get
			{
				return this.GetTable<PioneerET_Frac_Locations_Well>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Locations_Fleets> PioneerET_Locations_Fleets
		{
			get
			{
				return this.GetTable<PioneerET_Locations_Fleets>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Locations_Silos> PioneerET_Locations_Silos
		{
			get
			{
				return this.GetTable<PioneerET_Locations_Silos>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Notes> PioneerET_Notes
		{
			get
			{
				return this.GetTable<PioneerET_Notes>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Notifications> PioneerET_Notifications
		{
			get
			{
				return this.GetTable<PioneerET_Notifications>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Notifications_Recipients> PioneerET_Notifications_Recipients
		{
			get
			{
				return this.GetTable<PioneerET_Notifications_Recipients>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Options> PioneerET_Options
		{
			get
			{
				return this.GetTable<PioneerET_Options>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Out_For_Repair> PioneerET_Out_For_Repair
		{
			get
			{
				return this.GetTable<PioneerET_Out_For_Repair>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Repair_Locations> PioneerET_Repair_Locations
		{
			get
			{
				return this.GetTable<PioneerET_Repair_Locations>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_SiloSets> PioneerET_SiloSets
		{
			get
			{
				return this.GetTable<PioneerET_SiloSets>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Standards> PioneerET_Standards
		{
			get
			{
				return this.GetTable<PioneerET_Standards>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Team_Management> PioneerET_Team_Management
		{
			get
			{
				return this.GetTable<PioneerET_Team_Management>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_UserRole_LDAPGroup> PioneerET_UserRole_LDAPGroup
		{
			get
			{
				return this.GetTable<PioneerET_UserRole_LDAPGroup>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Users_from_LDAP> PioneerET_Users_from_LDAP
		{
			get
			{
				return this.GetTable<PioneerET_Users_from_LDAP>();
			}
		}
		
		public System.Data.Linq.Table<PioneerET_Yard> PioneerET_Yard
		{
			get
			{
				return this.GetTable<PioneerET_Yard>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Assigned_Equipment")]
	public partial class PioneerET_Assigned_Equipment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private int _Fleet_Title;
		
		private System.Nullable<int> _Unit_Type;
		
		private int _Tractor_ID;
		
		private int _Trailer_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnFleet_TitleChanging(int value);
    partial void OnFleet_TitleChanged();
    partial void OnUnit_TypeChanging(System.Nullable<int> value);
    partial void OnUnit_TypeChanged();
    partial void OnTractor_IDChanging(int value);
    partial void OnTractor_IDChanged();
    partial void OnTrailer_IDChanging(int value);
    partial void OnTrailer_IDChanged();
    #endregion
		
		public PioneerET_Assigned_Equipment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fleet_Title", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fleet_Title
		{
			get
			{
				return this._Fleet_Title;
			}
			set
			{
				if ((this._Fleet_Title != value))
				{
					this.OnFleet_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fleet_Title = value;
					this.SendPropertyChanged("Fleet_Title");
					this.OnFleet_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Type", DbType="Int")]
		public System.Nullable<int> Unit_Type
		{
			get
			{
				return this._Unit_Type;
			}
			set
			{
				if ((this._Unit_Type != value))
				{
					this.OnUnit_TypeChanging(value);
					this.SendPropertyChanging();
					this._Unit_Type = value;
					this.SendPropertyChanged("Unit_Type");
					this.OnUnit_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Equipments_Inventory")]
	public partial class PioneerET_Equipments_Inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private int _Equipment_ID;
		
		private System.Nullable<int> _Unit_Type;
		
		private string _Title;
		
		private System.Nullable<int> _Wet_Kit;
		
		private System.Nullable<int> _Fluid_End;
		
		private System.Nullable<bool> _CNG;
		
		private System.Nullable<bool> _Iron_Maintenance;
		
		private System.Nullable<bool> _ETech_Maintenance;
		
		private System.Nullable<bool> _Operational_Testing;
		
		private string _Notes;
		
		private System.Nullable<bool> _Activation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnEquipment_IDChanging(int value);
    partial void OnEquipment_IDChanged();
    partial void OnUnit_TypeChanging(System.Nullable<int> value);
    partial void OnUnit_TypeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnWet_KitChanging(System.Nullable<int> value);
    partial void OnWet_KitChanged();
    partial void OnFluid_EndChanging(System.Nullable<int> value);
    partial void OnFluid_EndChanged();
    partial void OnCNGChanging(System.Nullable<bool> value);
    partial void OnCNGChanged();
    partial void OnIron_MaintenanceChanging(System.Nullable<bool> value);
    partial void OnIron_MaintenanceChanged();
    partial void OnETech_MaintenanceChanging(System.Nullable<bool> value);
    partial void OnETech_MaintenanceChanged();
    partial void OnOperational_TestingChanging(System.Nullable<bool> value);
    partial void OnOperational_TestingChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnActivationChanging(System.Nullable<bool> value);
    partial void OnActivationChanged();
    #endregion
		
		public PioneerET_Equipments_Inventory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Equipment_ID
		{
			get
			{
				return this._Equipment_ID;
			}
			set
			{
				if ((this._Equipment_ID != value))
				{
					this.OnEquipment_IDChanging(value);
					this.SendPropertyChanging();
					this._Equipment_ID = value;
					this.SendPropertyChanged("Equipment_ID");
					this.OnEquipment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Type", DbType="Int")]
		public System.Nullable<int> Unit_Type
		{
			get
			{
				return this._Unit_Type;
			}
			set
			{
				if ((this._Unit_Type != value))
				{
					this.OnUnit_TypeChanging(value);
					this.SendPropertyChanging();
					this._Unit_Type = value;
					this.SendPropertyChanged("Unit_Type");
					this.OnUnit_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wet_Kit", DbType="Int")]
		public System.Nullable<int> Wet_Kit
		{
			get
			{
				return this._Wet_Kit;
			}
			set
			{
				if ((this._Wet_Kit != value))
				{
					this.OnWet_KitChanging(value);
					this.SendPropertyChanging();
					this._Wet_Kit = value;
					this.SendPropertyChanged("Wet_Kit");
					this.OnWet_KitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fluid_End", DbType="Int")]
		public System.Nullable<int> Fluid_End
		{
			get
			{
				return this._Fluid_End;
			}
			set
			{
				if ((this._Fluid_End != value))
				{
					this.OnFluid_EndChanging(value);
					this.SendPropertyChanging();
					this._Fluid_End = value;
					this.SendPropertyChanged("Fluid_End");
					this.OnFluid_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNG", DbType="Bit")]
		public System.Nullable<bool> CNG
		{
			get
			{
				return this._CNG;
			}
			set
			{
				if ((this._CNG != value))
				{
					this.OnCNGChanging(value);
					this.SendPropertyChanging();
					this._CNG = value;
					this.SendPropertyChanged("CNG");
					this.OnCNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iron_Maintenance", DbType="Bit")]
		public System.Nullable<bool> Iron_Maintenance
		{
			get
			{
				return this._Iron_Maintenance;
			}
			set
			{
				if ((this._Iron_Maintenance != value))
				{
					this.OnIron_MaintenanceChanging(value);
					this.SendPropertyChanging();
					this._Iron_Maintenance = value;
					this.SendPropertyChanged("Iron_Maintenance");
					this.OnIron_MaintenanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETech_Maintenance", DbType="Bit")]
		public System.Nullable<bool> ETech_Maintenance
		{
			get
			{
				return this._ETech_Maintenance;
			}
			set
			{
				if ((this._ETech_Maintenance != value))
				{
					this.OnETech_MaintenanceChanging(value);
					this.SendPropertyChanging();
					this._ETech_Maintenance = value;
					this.SendPropertyChanged("ETech_Maintenance");
					this.OnETech_MaintenanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operational_Testing", DbType="Bit")]
		public System.Nullable<bool> Operational_Testing
		{
			get
			{
				return this._Operational_Testing;
			}
			set
			{
				if ((this._Operational_Testing != value))
				{
					this.OnOperational_TestingChanging(value);
					this.SendPropertyChanging();
					this._Operational_Testing = value;
					this.SendPropertyChanged("Operational_Testing");
					this.OnOperational_TestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(1)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activation", DbType="Bit")]
		public System.Nullable<bool> Activation
		{
			get
			{
				return this._Activation;
			}
			set
			{
				if ((this._Activation != value))
				{
					this.OnActivationChanging(value);
					this.SendPropertyChanging();
					this._Activation = value;
					this.SendPropertyChanged("Activation");
					this.OnActivationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Fleets_Management")]
	public partial class PioneerET_Fleets_Management : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Fleet_Title;
		
		private System.Nullable<bool> _Type;
		
		private string _Supervisor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnFleet_TitleChanging(string value);
    partial void OnFleet_TitleChanged();
    partial void OnTypeChanging(System.Nullable<bool> value);
    partial void OnTypeChanged();
    partial void OnSupervisorChanging(string value);
    partial void OnSupervisorChanged();
    #endregion
		
		public PioneerET_Fleets_Management()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fleet_Title", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Fleet_Title
		{
			get
			{
				return this._Fleet_Title;
			}
			set
			{
				if ((this._Fleet_Title != value))
				{
					this.OnFleet_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fleet_Title = value;
					this.SendPropertyChanged("Fleet_Title");
					this.OnFleet_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Bit")]
		public System.Nullable<bool> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(100)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this.OnSupervisorChanging(value);
					this.SendPropertyChanging();
					this._Supervisor = value;
					this.SendPropertyChanged("Supervisor");
					this.OnSupervisorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Frac_Locations")]
	public partial class PioneerET_Frac_Locations : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Title;
		
		private System.Nullable<int> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    #endregion
		
		public PioneerET_Frac_Locations()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Frac_Locations_Headcount")]
	public partial class PioneerET_Frac_Locations_Headcount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HeadCount;
		
		private System.Nullable<int> _Location;
		
		private System.Nullable<System.DateTime> _HeadCount_Timestamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHeadCountChanging(System.Nullable<int> value);
    partial void OnHeadCountChanged();
    partial void OnLocationChanging(System.Nullable<int> value);
    partial void OnLocationChanged();
    partial void OnHeadCount_TimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnHeadCount_TimestampChanged();
    #endregion
		
		public PioneerET_Frac_Locations_Headcount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadCount", DbType="Int")]
		public System.Nullable<int> HeadCount
		{
			get
			{
				return this._HeadCount;
			}
			set
			{
				if ((this._HeadCount != value))
				{
					this.OnHeadCountChanging(value);
					this.SendPropertyChanging();
					this._HeadCount = value;
					this.SendPropertyChanged("HeadCount");
					this.OnHeadCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="Int")]
		public System.Nullable<int> Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadCount_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> HeadCount_Timestamp
		{
			get
			{
				return this._HeadCount_Timestamp;
			}
			set
			{
				if ((this._HeadCount_Timestamp != value))
				{
					this.OnHeadCount_TimestampChanging(value);
					this.SendPropertyChanging();
					this._HeadCount_Timestamp = value;
					this.SendPropertyChanged("HeadCount_Timestamp");
					this.OnHeadCount_TimestampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Frac_Locations_Well")]
	public partial class PioneerET_Frac_Locations_Well : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _LocationID;
		
		private System.Nullable<int> _Team_Name;
		
		private string _Well_Identifier;
		
		private System.Nullable<int> _Planned_Frac_Stages;
		
		private System.Nullable<int> _Completed_Frac_Stages;
		
		private System.Nullable<System.DateTime> _Projected_Frac_Start_Date;
		
		private System.Nullable<System.DateTime> _Frac_End_Date;
		
		private System.Nullable<int> _Frac_Status;
		
		private System.Nullable<int> _Sand_Grade;
		
		private string _Volume;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnLocationIDChanging(System.Nullable<int> value);
    partial void OnLocationIDChanged();
    partial void OnTeam_NameChanging(System.Nullable<int> value);
    partial void OnTeam_NameChanged();
    partial void OnWell_IdentifierChanging(string value);
    partial void OnWell_IdentifierChanged();
    partial void OnPlanned_Frac_StagesChanging(System.Nullable<int> value);
    partial void OnPlanned_Frac_StagesChanged();
    partial void OnCompleted_Frac_StagesChanging(System.Nullable<int> value);
    partial void OnCompleted_Frac_StagesChanged();
    partial void OnProjected_Frac_Start_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnProjected_Frac_Start_DateChanged();
    partial void OnFrac_End_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnFrac_End_DateChanged();
    partial void OnFrac_StatusChanging(System.Nullable<int> value);
    partial void OnFrac_StatusChanged();
    partial void OnSand_GradeChanging(System.Nullable<int> value);
    partial void OnSand_GradeChanged();
    partial void OnVolumeChanging(string value);
    partial void OnVolumeChanged();
    #endregion
		
		public PioneerET_Frac_Locations_Well()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int")]
		public System.Nullable<int> LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team_Name", DbType="Int")]
		public System.Nullable<int> Team_Name
		{
			get
			{
				return this._Team_Name;
			}
			set
			{
				if ((this._Team_Name != value))
				{
					this.OnTeam_NameChanging(value);
					this.SendPropertyChanging();
					this._Team_Name = value;
					this.SendPropertyChanged("Team_Name");
					this.OnTeam_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Well_Identifier", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Well_Identifier
		{
			get
			{
				return this._Well_Identifier;
			}
			set
			{
				if ((this._Well_Identifier != value))
				{
					this.OnWell_IdentifierChanging(value);
					this.SendPropertyChanging();
					this._Well_Identifier = value;
					this.SendPropertyChanged("Well_Identifier");
					this.OnWell_IdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Planned_Frac_Stages", DbType="Int")]
		public System.Nullable<int> Planned_Frac_Stages
		{
			get
			{
				return this._Planned_Frac_Stages;
			}
			set
			{
				if ((this._Planned_Frac_Stages != value))
				{
					this.OnPlanned_Frac_StagesChanging(value);
					this.SendPropertyChanging();
					this._Planned_Frac_Stages = value;
					this.SendPropertyChanged("Planned_Frac_Stages");
					this.OnPlanned_Frac_StagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completed_Frac_Stages", DbType="Int")]
		public System.Nullable<int> Completed_Frac_Stages
		{
			get
			{
				return this._Completed_Frac_Stages;
			}
			set
			{
				if ((this._Completed_Frac_Stages != value))
				{
					this.OnCompleted_Frac_StagesChanging(value);
					this.SendPropertyChanging();
					this._Completed_Frac_Stages = value;
					this.SendPropertyChanged("Completed_Frac_Stages");
					this.OnCompleted_Frac_StagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Projected_Frac_Start_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Projected_Frac_Start_Date
		{
			get
			{
				return this._Projected_Frac_Start_Date;
			}
			set
			{
				if ((this._Projected_Frac_Start_Date != value))
				{
					this.OnProjected_Frac_Start_DateChanging(value);
					this.SendPropertyChanging();
					this._Projected_Frac_Start_Date = value;
					this.SendPropertyChanged("Projected_Frac_Start_Date");
					this.OnProjected_Frac_Start_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frac_End_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Frac_End_Date
		{
			get
			{
				return this._Frac_End_Date;
			}
			set
			{
				if ((this._Frac_End_Date != value))
				{
					this.OnFrac_End_DateChanging(value);
					this.SendPropertyChanging();
					this._Frac_End_Date = value;
					this.SendPropertyChanged("Frac_End_Date");
					this.OnFrac_End_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frac_Status", DbType="Int")]
		public System.Nullable<int> Frac_Status
		{
			get
			{
				return this._Frac_Status;
			}
			set
			{
				if ((this._Frac_Status != value))
				{
					this.OnFrac_StatusChanging(value);
					this.SendPropertyChanging();
					this._Frac_Status = value;
					this.SendPropertyChanged("Frac_Status");
					this.OnFrac_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sand_Grade", DbType="Int")]
		public System.Nullable<int> Sand_Grade
		{
			get
			{
				return this._Sand_Grade;
			}
			set
			{
				if ((this._Sand_Grade != value))
				{
					this.OnSand_GradeChanging(value);
					this.SendPropertyChanging();
					this._Sand_Grade = value;
					this.SendPropertyChanged("Sand_Grade");
					this.OnSand_GradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="VarChar(100)")]
		public string Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Locations_Fleets")]
	public partial class PioneerET_Locations_Fleets : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Title;
		
		private int _Trailer_ID;
		
		private int _Tractor_ID;
		
		private System.Nullable<int> _Tractor_Status;
		
		private System.Nullable<int> _Trailer_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTitleChanging(int value);
    partial void OnTitleChanged();
    partial void OnTrailer_IDChanging(int value);
    partial void OnTrailer_IDChanged();
    partial void OnTractor_IDChanging(int value);
    partial void OnTractor_IDChanged();
    partial void OnTractor_StatusChanging(System.Nullable<int> value);
    partial void OnTractor_StatusChanged();
    partial void OnTrailer_StatusChanging(System.Nullable<int> value);
    partial void OnTrailer_StatusChanged();
    #endregion
		
		public PioneerET_Locations_Fleets()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_Status", DbType="Int")]
		public System.Nullable<int> Tractor_Status
		{
			get
			{
				return this._Tractor_Status;
			}
			set
			{
				if ((this._Tractor_Status != value))
				{
					this.OnTractor_StatusChanging(value);
					this.SendPropertyChanging();
					this._Tractor_Status = value;
					this.SendPropertyChanged("Tractor_Status");
					this.OnTractor_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Status", DbType="Int")]
		public System.Nullable<int> Trailer_Status
		{
			get
			{
				return this._Trailer_Status;
			}
			set
			{
				if ((this._Trailer_Status != value))
				{
					this.OnTrailer_StatusChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Status = value;
					this.SendPropertyChanged("Trailer_Status");
					this.OnTrailer_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Locations_Silos")]
	public partial class PioneerET_Locations_Silos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Title;
		
		private int _Trailer_ID;
		
		private int _Tractor_ID;
		
		private System.Nullable<int> _Tractor_Status;
		
		private System.Nullable<int> _Trailer_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTitleChanging(int value);
    partial void OnTitleChanged();
    partial void OnTrailer_IDChanging(int value);
    partial void OnTrailer_IDChanged();
    partial void OnTractor_IDChanging(int value);
    partial void OnTractor_IDChanged();
    partial void OnTractor_StatusChanging(System.Nullable<int> value);
    partial void OnTractor_StatusChanged();
    partial void OnTrailer_StatusChanging(System.Nullable<int> value);
    partial void OnTrailer_StatusChanged();
    #endregion
		
		public PioneerET_Locations_Silos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_Status", DbType="Int")]
		public System.Nullable<int> Tractor_Status
		{
			get
			{
				return this._Tractor_Status;
			}
			set
			{
				if ((this._Tractor_Status != value))
				{
					this.OnTractor_StatusChanging(value);
					this.SendPropertyChanging();
					this._Tractor_Status = value;
					this.SendPropertyChanged("Tractor_Status");
					this.OnTractor_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Status", DbType="Int")]
		public System.Nullable<int> Trailer_Status
		{
			get
			{
				return this._Trailer_Status;
			}
			set
			{
				if ((this._Trailer_Status != value))
				{
					this.OnTrailer_StatusChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Status = value;
					this.SendPropertyChanged("Trailer_Status");
					this.OnTrailer_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Notes")]
	public partial class PioneerET_Notes
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _EquipmentID;
		
		private string _PioneerUserIdentifier;
		
		private System.Nullable<int> _Operation_Type;
		
		private System.Nullable<int> _Location_ID;
		
		private System.Nullable<System.DateTime> _Notes_Date;
		
		private string _Notes;
		
		private System.Nullable<int> _Created_By;
		
		public PioneerET_Notes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentID", DbType="Int")]
		public System.Nullable<int> EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				if ((this._EquipmentID != value))
				{
					this._EquipmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PioneerUserIdentifier", DbType="VarChar(100)")]
		public string PioneerUserIdentifier
		{
			get
			{
				return this._PioneerUserIdentifier;
			}
			set
			{
				if ((this._PioneerUserIdentifier != value))
				{
					this._PioneerUserIdentifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation_Type", DbType="Int")]
		public System.Nullable<int> Operation_Type
		{
			get
			{
				return this._Operation_Type;
			}
			set
			{
				if ((this._Operation_Type != value))
				{
					this._Operation_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_ID", DbType="Int")]
		public System.Nullable<int> Location_ID
		{
			get
			{
				return this._Location_ID;
			}
			set
			{
				if ((this._Location_ID != value))
				{
					this._Location_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Notes_Date
		{
			get
			{
				return this._Notes_Date;
			}
			set
			{
				if ((this._Notes_Date != value))
				{
					this._Notes_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="Int")]
		public System.Nullable<int> Created_By
		{
			get
			{
				return this._Created_By;
			}
			set
			{
				if ((this._Created_By != value))
				{
					this._Created_By = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Notifications")]
	public partial class PioneerET_Notifications : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _Sub_Type;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _Timestamp;
		
		private System.Nullable<int> _Priority;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnSub_TypeChanging(System.Nullable<int> value);
    partial void OnSub_TypeChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestampChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    #endregion
		
		public PioneerET_Notifications()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Type", DbType="Int")]
		public System.Nullable<int> Sub_Type
		{
			get
			{
				return this._Sub_Type;
			}
			set
			{
				if ((this._Sub_Type != value))
				{
					this.OnSub_TypeChanging(value);
					this.SendPropertyChanging();
					this._Sub_Type = value;
					this.SendPropertyChanged("Sub_Type");
					this.OnSub_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(500)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Notifications_Recipients")]
	public partial class PioneerET_Notifications_Recipients : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private int _Notification_ID;
		
		private int _User_ID;
		
		private System.Nullable<System.DateTime> _Send_Date;
		
		private System.Nullable<System.DateTime> _Read_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnNotification_IDChanging(int value);
    partial void OnNotification_IDChanged();
    partial void OnUser_IDChanging(int value);
    partial void OnUser_IDChanged();
    partial void OnSend_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnSend_DateChanged();
    partial void OnRead_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRead_DateChanged();
    #endregion
		
		public PioneerET_Notifications_Recipients()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notification_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Notification_ID
		{
			get
			{
				return this._Notification_ID;
			}
			set
			{
				if ((this._Notification_ID != value))
				{
					this.OnNotification_IDChanging(value);
					this.SendPropertyChanging();
					this._Notification_ID = value;
					this.SendPropertyChanged("Notification_ID");
					this.OnNotification_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Send_Date
		{
			get
			{
				return this._Send_Date;
			}
			set
			{
				if ((this._Send_Date != value))
				{
					this.OnSend_DateChanging(value);
					this.SendPropertyChanging();
					this._Send_Date = value;
					this.SendPropertyChanged("Send_Date");
					this.OnSend_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Read_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Read_Date
		{
			get
			{
				return this._Read_Date;
			}
			set
			{
				if ((this._Read_Date != value))
				{
					this.OnRead_DateChanging(value);
					this.SendPropertyChanging();
					this._Read_Date = value;
					this.SendPropertyChanged("Read_Date");
					this.OnRead_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Options")]
	public partial class PioneerET_Options : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Title;
		
		private int _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    #endregion
		
		public PioneerET_Options()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(500) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Out_For_Repair")]
	public partial class PioneerET_Out_For_Repair : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private int _OFR_Location;
		
		private int _Trailer_ID;
		
		private int _Tractor_ID;
		
		private System.Nullable<int> _Unit_Type;
		
		private string _Additional_Notes;
		
		private System.Nullable<System.DateTime> _In_Date;
		
		private System.Nullable<System.DateTime> _Out_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnOFR_LocationChanging(int value);
    partial void OnOFR_LocationChanged();
    partial void OnTrailer_IDChanging(int value);
    partial void OnTrailer_IDChanged();
    partial void OnTractor_IDChanging(int value);
    partial void OnTractor_IDChanged();
    partial void OnUnit_TypeChanging(System.Nullable<int> value);
    partial void OnUnit_TypeChanged();
    partial void OnAdditional_NotesChanging(string value);
    partial void OnAdditional_NotesChanged();
    partial void OnIn_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnIn_DateChanged();
    partial void OnOut_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnOut_DateChanged();
    #endregion
		
		public PioneerET_Out_For_Repair()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFR_Location", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OFR_Location
		{
			get
			{
				return this._OFR_Location;
			}
			set
			{
				if ((this._OFR_Location != value))
				{
					this.OnOFR_LocationChanging(value);
					this.SendPropertyChanging();
					this._OFR_Location = value;
					this.SendPropertyChanged("OFR_Location");
					this.OnOFR_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Type", DbType="Int")]
		public System.Nullable<int> Unit_Type
		{
			get
			{
				return this._Unit_Type;
			}
			set
			{
				if ((this._Unit_Type != value))
				{
					this.OnUnit_TypeChanging(value);
					this.SendPropertyChanging();
					this._Unit_Type = value;
					this.SendPropertyChanged("Unit_Type");
					this.OnUnit_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Additional_Notes", DbType="VarChar(1)")]
		public string Additional_Notes
		{
			get
			{
				return this._Additional_Notes;
			}
			set
			{
				if ((this._Additional_Notes != value))
				{
					this.OnAdditional_NotesChanging(value);
					this.SendPropertyChanging();
					this._Additional_Notes = value;
					this.SendPropertyChanged("Additional_Notes");
					this.OnAdditional_NotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_In_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> In_Date
		{
			get
			{
				return this._In_Date;
			}
			set
			{
				if ((this._In_Date != value))
				{
					this.OnIn_DateChanging(value);
					this.SendPropertyChanging();
					this._In_Date = value;
					this.SendPropertyChanged("In_Date");
					this.OnIn_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Out_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Out_Date
		{
			get
			{
				return this._Out_Date;
			}
			set
			{
				if ((this._Out_Date != value))
				{
					this.OnOut_DateChanging(value);
					this.SendPropertyChanging();
					this._Out_Date = value;
					this.SendPropertyChanged("Out_Date");
					this.OnOut_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Repair_Locations")]
	public partial class PioneerET_Repair_Locations : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public PioneerET_Repair_Locations()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_SiloSets")]
	public partial class PioneerET_SiloSets : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Title;
		
		private System.Nullable<int> _Unit_Type;
		
		private int _Tractor_ID;
		
		private int _Trailer_ID;
		
		private System.Nullable<System.DateTime> _Filter_1_Change_Date;
		
		private System.Nullable<System.DateTime> _Filter_2_Change_Date;
		
		private System.Nullable<System.DateTime> _Filter_3_Change_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnUnit_TypeChanging(System.Nullable<int> value);
    partial void OnUnit_TypeChanged();
    partial void OnTractor_IDChanging(int value);
    partial void OnTractor_IDChanged();
    partial void OnTrailer_IDChanging(int value);
    partial void OnTrailer_IDChanged();
    partial void OnFilter_1_Change_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnFilter_1_Change_DateChanged();
    partial void OnFilter_2_Change_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnFilter_2_Change_DateChanged();
    partial void OnFilter_3_Change_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnFilter_3_Change_DateChanged();
    #endregion
		
		public PioneerET_SiloSets()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Type", DbType="Int")]
		public System.Nullable<int> Unit_Type
		{
			get
			{
				return this._Unit_Type;
			}
			set
			{
				if ((this._Unit_Type != value))
				{
					this.OnUnit_TypeChanging(value);
					this.SendPropertyChanging();
					this._Unit_Type = value;
					this.SendPropertyChanged("Unit_Type");
					this.OnUnit_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filter_1_Change_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Filter_1_Change_Date
		{
			get
			{
				return this._Filter_1_Change_Date;
			}
			set
			{
				if ((this._Filter_1_Change_Date != value))
				{
					this.OnFilter_1_Change_DateChanging(value);
					this.SendPropertyChanging();
					this._Filter_1_Change_Date = value;
					this.SendPropertyChanged("Filter_1_Change_Date");
					this.OnFilter_1_Change_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filter_2_Change_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Filter_2_Change_Date
		{
			get
			{
				return this._Filter_2_Change_Date;
			}
			set
			{
				if ((this._Filter_2_Change_Date != value))
				{
					this.OnFilter_2_Change_DateChanging(value);
					this.SendPropertyChanging();
					this._Filter_2_Change_Date = value;
					this.SendPropertyChanged("Filter_2_Change_Date");
					this.OnFilter_2_Change_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filter_3_Change_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Filter_3_Change_Date
		{
			get
			{
				return this._Filter_3_Change_Date;
			}
			set
			{
				if ((this._Filter_3_Change_Date != value))
				{
					this.OnFilter_3_Change_DateChanging(value);
					this.SendPropertyChanging();
					this._Filter_3_Change_Date = value;
					this.SendPropertyChanged("Filter_3_Change_Date");
					this.OnFilter_3_Change_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Standards")]
	public partial class PioneerET_Standards : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _Name;
		
		private System.Nullable<int> _Default_Value;
		
		private System.Nullable<int> _Value;
		
		private System.Nullable<bool> _Is_Editable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDefault_ValueChanging(System.Nullable<int> value);
    partial void OnDefault_ValueChanged();
    partial void OnValueChanging(System.Nullable<int> value);
    partial void OnValueChanged();
    partial void OnIs_EditableChanging(System.Nullable<bool> value);
    partial void OnIs_EditableChanged();
    #endregion
		
		public PioneerET_Standards()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Default_Value", DbType="Int")]
		public System.Nullable<int> Default_Value
		{
			get
			{
				return this._Default_Value;
			}
			set
			{
				if ((this._Default_Value != value))
				{
					this.OnDefault_ValueChanging(value);
					this.SendPropertyChanging();
					this._Default_Value = value;
					this.SendPropertyChanged("Default_Value");
					this.OnDefault_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Int")]
		public System.Nullable<int> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Editable", DbType="Bit")]
		public System.Nullable<bool> Is_Editable
		{
			get
			{
				return this._Is_Editable;
			}
			set
			{
				if ((this._Is_Editable != value))
				{
					this.OnIs_EditableChanging(value);
					this.SendPropertyChanging();
					this._Is_Editable = value;
					this.SendPropertyChanged("Is_Editable");
					this.OnIs_EditableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Team_Management")]
	public partial class PioneerET_Team_Management : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _PioneerUserIdentifier;
		
		private string _Title;
		
		private System.Nullable<int> _Lead;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnPioneerUserIdentifierChanging(string value);
    partial void OnPioneerUserIdentifierChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnLeadChanging(System.Nullable<int> value);
    partial void OnLeadChanged();
    #endregion
		
		public PioneerET_Team_Management()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PioneerUserIdentifier", DbType="VarChar(100)")]
		public string PioneerUserIdentifier
		{
			get
			{
				return this._PioneerUserIdentifier;
			}
			set
			{
				if ((this._PioneerUserIdentifier != value))
				{
					this.OnPioneerUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._PioneerUserIdentifier = value;
					this.SendPropertyChanged("PioneerUserIdentifier");
					this.OnPioneerUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lead", DbType="Int")]
		public System.Nullable<int> Lead
		{
			get
			{
				return this._Lead;
			}
			set
			{
				if ((this._Lead != value))
				{
					this.OnLeadChanging(value);
					this.SendPropertyChanging();
					this._Lead = value;
					this.SendPropertyChanged("Lead");
					this.OnLeadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_UserRole_LDAPGroup")]
	public partial class PioneerET_UserRole_LDAPGroup
	{
		
		private System.Nullable<int> _ID;
		
		private string _Role;
		
		private string _Group;
		
		public PioneerET_UserRole_LDAPGroup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(500)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group", DbType="VarChar(500)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Users_from_LDAP")]
	public partial class PioneerET_Users_from_LDAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PioneerUserIdentifier;
		
		private string _EmailAddress;
		
		private System.Nullable<bool> _IsActive;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MemberOfGroups;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPioneerUserIdentifierChanging(string value);
    partial void OnPioneerUserIdentifierChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMemberOfGroupsChanging(string value);
    partial void OnMemberOfGroupsChanged();
    #endregion
		
		public PioneerET_Users_from_LDAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PioneerUserIdentifier", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PioneerUserIdentifier
		{
			get
			{
				return this._PioneerUserIdentifier;
			}
			set
			{
				if ((this._PioneerUserIdentifier != value))
				{
					this.OnPioneerUserIdentifierChanging(value);
					this.SendPropertyChanging();
					this._PioneerUserIdentifier = value;
					this.SendPropertyChanged("PioneerUserIdentifier");
					this.OnPioneerUserIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(100)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="isActive", Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(255)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(255)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberOfGroups", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string MemberOfGroups
		{
			get
			{
				return this._MemberOfGroups;
			}
			set
			{
				if ((this._MemberOfGroups != value))
				{
					this.OnMemberOfGroupsChanging(value);
					this.SendPropertyChanging();
					this._MemberOfGroups = value;
					this.SendPropertyChanged("MemberOfGroups");
					this.OnMemberOfGroupsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PioneerET_Yard")]
	public partial class PioneerET_Yard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Tractor_ID;
		
		private System.Nullable<int> _Tractor_Maintenance;
		
		private System.Nullable<int> _Trailer_ID;
		
		private System.Nullable<int> _Trailer_Fluid_End;
		
		private System.Nullable<int> _Trailer_Maintenance;
		
		private System.Nullable<int> _Trailer_Iron;
		
		private System.Nullable<int> _Trailer_ETech;
		
		private System.Nullable<int> _Trailer_Operational_Testing;
		
		private string _Notes;
		
		private System.Nullable<System.DateTime> _In_Date;
		
		private System.Nullable<System.DateTime> _Out_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTractor_IDChanging(System.Nullable<int> value);
    partial void OnTractor_IDChanged();
    partial void OnTractor_MaintenanceChanging(System.Nullable<int> value);
    partial void OnTractor_MaintenanceChanged();
    partial void OnTrailer_IDChanging(System.Nullable<int> value);
    partial void OnTrailer_IDChanged();
    partial void OnTrailer_Fluid_EndChanging(System.Nullable<int> value);
    partial void OnTrailer_Fluid_EndChanged();
    partial void OnTrailer_MaintenanceChanging(System.Nullable<int> value);
    partial void OnTrailer_MaintenanceChanged();
    partial void OnTrailer_IronChanging(System.Nullable<int> value);
    partial void OnTrailer_IronChanged();
    partial void OnTrailer_ETechChanging(System.Nullable<int> value);
    partial void OnTrailer_ETechChanged();
    partial void OnTrailer_Operational_TestingChanging(System.Nullable<int> value);
    partial void OnTrailer_Operational_TestingChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnIn_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnIn_DateChanged();
    partial void OnOut_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnOut_DateChanged();
    #endregion
		
		public PioneerET_Yard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_ID", DbType="Int")]
		public System.Nullable<int> Tractor_ID
		{
			get
			{
				return this._Tractor_ID;
			}
			set
			{
				if ((this._Tractor_ID != value))
				{
					this.OnTractor_IDChanging(value);
					this.SendPropertyChanging();
					this._Tractor_ID = value;
					this.SendPropertyChanged("Tractor_ID");
					this.OnTractor_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tractor_Maintenance", DbType="Int")]
		public System.Nullable<int> Tractor_Maintenance
		{
			get
			{
				return this._Tractor_Maintenance;
			}
			set
			{
				if ((this._Tractor_Maintenance != value))
				{
					this.OnTractor_MaintenanceChanging(value);
					this.SendPropertyChanging();
					this._Tractor_Maintenance = value;
					this.SendPropertyChanged("Tractor_Maintenance");
					this.OnTractor_MaintenanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ID", DbType="Int")]
		public System.Nullable<int> Trailer_ID
		{
			get
			{
				return this._Trailer_ID;
			}
			set
			{
				if ((this._Trailer_ID != value))
				{
					this.OnTrailer_IDChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ID = value;
					this.SendPropertyChanged("Trailer_ID");
					this.OnTrailer_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Fluid_End", DbType="Int")]
		public System.Nullable<int> Trailer_Fluid_End
		{
			get
			{
				return this._Trailer_Fluid_End;
			}
			set
			{
				if ((this._Trailer_Fluid_End != value))
				{
					this.OnTrailer_Fluid_EndChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Fluid_End = value;
					this.SendPropertyChanged("Trailer_Fluid_End");
					this.OnTrailer_Fluid_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Maintenance", DbType="Int")]
		public System.Nullable<int> Trailer_Maintenance
		{
			get
			{
				return this._Trailer_Maintenance;
			}
			set
			{
				if ((this._Trailer_Maintenance != value))
				{
					this.OnTrailer_MaintenanceChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Maintenance = value;
					this.SendPropertyChanged("Trailer_Maintenance");
					this.OnTrailer_MaintenanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Iron", DbType="Int")]
		public System.Nullable<int> Trailer_Iron
		{
			get
			{
				return this._Trailer_Iron;
			}
			set
			{
				if ((this._Trailer_Iron != value))
				{
					this.OnTrailer_IronChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Iron = value;
					this.SendPropertyChanged("Trailer_Iron");
					this.OnTrailer_IronChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_ETech", DbType="Int")]
		public System.Nullable<int> Trailer_ETech
		{
			get
			{
				return this._Trailer_ETech;
			}
			set
			{
				if ((this._Trailer_ETech != value))
				{
					this.OnTrailer_ETechChanging(value);
					this.SendPropertyChanging();
					this._Trailer_ETech = value;
					this.SendPropertyChanged("Trailer_ETech");
					this.OnTrailer_ETechChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trailer_Operational_Testing", DbType="Int")]
		public System.Nullable<int> Trailer_Operational_Testing
		{
			get
			{
				return this._Trailer_Operational_Testing;
			}
			set
			{
				if ((this._Trailer_Operational_Testing != value))
				{
					this.OnTrailer_Operational_TestingChanging(value);
					this.SendPropertyChanging();
					this._Trailer_Operational_Testing = value;
					this.SendPropertyChanged("Trailer_Operational_Testing");
					this.OnTrailer_Operational_TestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(1)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_In_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> In_Date
		{
			get
			{
				return this._In_Date;
			}
			set
			{
				if ((this._In_Date != value))
				{
					this.OnIn_DateChanging(value);
					this.SendPropertyChanging();
					this._In_Date = value;
					this.SendPropertyChanged("In_Date");
					this.OnIn_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Out_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Out_Date
		{
			get
			{
				return this._Out_Date;
			}
			set
			{
				if ((this._Out_Date != value))
				{
					this.OnOut_DateChanging(value);
					this.SendPropertyChanging();
					this._Out_Date = value;
					this.SendPropertyChanged("Out_Date");
					this.OnOut_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
